"""Access to the bundled hardened Dockerfile templates."""

from __future__ import annotations

from importlib import resources
from typing import TYPE_CHECKING, NamedTuple

if TYPE_CHECKING:
    from collections.abc import Iterator

TEMPLATE_PACKAGE = "dockerls.infrastructure.templates.hardening"

# A minimal .dockerignore shipped alongside every template: without it the
# `COPY . .` in the template is exactly the mistake the template exists to
# prevent, and `dockerignore_present` would fail on freshly generated files.
DEFAULT_DOCKERIGNORE = """\
# Generated by `dockerls templates generate`
.git
.gitignore
.env
.env.*
.dockerignore
Dockerfile*
**/.aws
**/.ssh
**/*.pem
**/*.key
node_modules
__pycache__
*.pyc
.venv
venv
target
dist
build
.pytest_cache
.mypy_cache
.ruff_cache
logs
.dockerls
"""


class Template(NamedTuple):
    name: str
    description: str
    default_port: int
    filename: str

    def read(self) -> str:
        return resources.files(TEMPLATE_PACKAGE).joinpath(self.filename).read_text(encoding="utf-8")


TEMPLATES: dict[str, Template] = {
    "node": Template(
        name="node",
        description="Node.js -- multi-stage, Alpine runtime, npm cache stripped, non-root",
        default_port=3000,
        filename="node.dockerfile",
    ),
    "python": Template(
        name="python",
        description="Python -- multi-stage wheels, Alpine runtime, --user install, non-root",
        default_port=8000,
        filename="python.dockerfile",
    ),
    "go": Template(
        name="go",
        description="Go -- static binary on scratch: no shell, no libc, no package manager",
        default_port=8080,
        filename="go.dockerfile",
    ),
    "java": Template(
        name="java",
        description="Java -- Maven builder, Temurin JRE Alpine runtime, container-aware heap",
        default_port=8080,
        filename="java.dockerfile",
    ),
}

# What a project has to contain for a template to be the obvious choice.
# Ordered most specific first so a polyglot repo picks its primary runtime.
DETECTION_MARKERS: tuple[tuple[str, str], ...] = (
    ("go", "go.mod"),
    ("java", "pom.xml"),
    ("java", "build.gradle"),
    ("java", "build.gradle.kts"),
    ("node", "package.json"),
    ("python", "pyproject.toml"),
    ("python", "requirements.txt"),
    ("python", "setup.py"),
)


def available_templates() -> Iterator[Template]:
    yield from TEMPLATES.values()


def get_template(name: str) -> Template:
    key = name.strip().lower()
    # "nodejs", "python3", "golang" are what people actually type.
    aliases = {"nodejs": "node", "js": "node", "python3": "python", "py": "python", "golang": "go"}
    key = aliases.get(key, key)
    if key not in TEMPLATES:
        supported = ", ".join(sorted(TEMPLATES))
        raise ValueError(f"Unknown template: {name}. Available: {supported}")
    return TEMPLATES[key]
